sudo: required # need sudo
services:
  - docker # install docker

before_install:
  - docker build -t rezadhah/docker-react-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true rezadhah/docker-react-dev npm run test -- --coverage --watchAll=false